/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AdminUtilisateursRouteImport } from './routes/admin-utilisateurs'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ComptableRouteImport } from './routes/comptable'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaddyRouteImport } from './routes/paddy'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as UsinageRouteImport } from './routes/usinage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin-utilisateurs',
  path: '/admin-utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptableRoute = ComptableRouteImport.update({
  id: '/comptable',
  path: '/comptable',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddyRoute = PaddyRouteImport.update({
  id: '/paddy',
  path: '/paddy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const UsinageRoute = UsinageRouteImport.update({
  id: '/usinage',
  path: '/usinage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
  id:
    | '__root__'
    | '/'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  CommercialRoute: typeof CommercialRoute
  ComptableRoute: typeof ComptableRoute
  GestionRoute: typeof GestionRoute
  LoginRoute: typeof LoginRoute
  PaddyRoute: typeof PaddyRoute
  PartenairesRoute: typeof PartenairesRoute
  ReportingRoute: typeof ReportingRoute
  UsinageRoute: typeof UsinageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-utilisateurs': {
      id: '/admin-utilisateurs'
      path: '/admin-utilisateurs'
      fullPath: '/admin-utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptable': {
      id: '/comptable'
      path: '/comptable'
      fullPath: '/comptable'
      preLoaderRoute: typeof ComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paddy': {
      id: '/paddy'
      path: '/paddy'
      fullPath: '/paddy'
      preLoaderRoute: typeof PaddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usinage': {
      id: '/usinage'
      path: '/usinage'
      fullPath: '/usinage'
      preLoaderRoute: typeof UsinageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  CommercialRoute: CommercialRoute,
  ComptableRoute: ComptableRoute,
  GestionRoute: GestionRoute,
  LoginRoute: LoginRoute,
  PaddyRoute: PaddyRoute,
  PartenairesRoute: PartenairesRoute,
  ReportingRoute: ReportingRoute,
  UsinageRoute: UsinageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
