/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsinageRouteImport } from './routes/usinage'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as PaddyRouteImport } from './routes/paddy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as ComptableRouteImport } from './routes/comptable'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as AdminUtilisateursRouteImport } from './routes/admin-utilisateurs'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AdminParametresRouteImport } from './routes/admin-parametres'
import { Route as AdminImportEcosRouteImport } from './routes/admin-import-ecos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const UsinageRoute = UsinageRouteImport.update({
  id: '/usinage',
  path: '/usinage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddyRoute = PaddyRouteImport.update({
  id: '/paddy',
  path: '/paddy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptableRoute = ComptableRouteImport.update({
  id: '/comptable',
  path: '/comptable',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin-utilisateurs',
  path: '/admin-utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin-parametres',
  path: '/admin-parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportEcosRoute = AdminImportEcosRouteImport.update({
  id: '/admin-import-ecos',
  path: '/admin-import-ecos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-import-ecos': typeof AdminImportEcosRoute
  '/admin-parametres': typeof AdminParametresRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-import-ecos': typeof AdminImportEcosRoute
  '/admin-parametres': typeof AdminParametresRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-import-ecos': typeof AdminImportEcosRoute
  '/admin-parametres': typeof AdminParametresRoute
  '/admin-setup': typeof AdminSetupRoute
  '/admin-utilisateurs': typeof AdminUtilisateursRoute
  '/commercial': typeof CommercialRoute
  '/comptable': typeof ComptableRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/paddy': typeof PaddyRoute
  '/partenaires': typeof PartenairesRoute
  '/reporting': typeof ReportingRoute
  '/usinage': typeof UsinageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-import-ecos'
    | '/admin-parametres'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/mcp'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-import-ecos'
    | '/admin-parametres'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/mcp'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin-import-ecos'
    | '/admin-parametres'
    | '/admin-setup'
    | '/admin-utilisateurs'
    | '/commercial'
    | '/comptable'
    | '/gestion'
    | '/login'
    | '/mcp'
    | '/paddy'
    | '/partenaires'
    | '/reporting'
    | '/usinage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminImportEcosRoute: typeof AdminImportEcosRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  CommercialRoute: typeof CommercialRoute
  ComptableRoute: typeof ComptableRoute
  GestionRoute: typeof GestionRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PaddyRoute: typeof PaddyRoute
  PartenairesRoute: typeof PartenairesRoute
  ReportingRoute: typeof ReportingRoute
  UsinageRoute: typeof UsinageRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usinage': {
      id: '/usinage'
      path: '/usinage'
      fullPath: '/usinage'
      preLoaderRoute: typeof UsinageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paddy': {
      id: '/paddy'
      path: '/paddy'
      fullPath: '/paddy'
      preLoaderRoute: typeof PaddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptable': {
      id: '/comptable'
      path: '/comptable'
      fullPath: '/comptable'
      preLoaderRoute: typeof ComptableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-utilisateurs': {
      id: '/admin-utilisateurs'
      path: '/admin-utilisateurs'
      fullPath: '/admin-utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-parametres': {
      id: '/admin-parametres'
      path: '/admin-parametres'
      fullPath: '/admin-parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-import-ecos': {
      id: '/admin-import-ecos'
      path: '/admin-import-ecos'
      fullPath: '/admin-import-ecos'
      preLoaderRoute: typeof AdminImportEcosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminImportEcosRoute: AdminImportEcosRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  CommercialRoute: CommercialRoute,
  ComptableRoute: ComptableRoute,
  GestionRoute: GestionRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PaddyRoute: PaddyRoute,
  PartenairesRoute: PartenairesRoute,
  ReportingRoute: ReportingRoute,
  UsinageRoute: UsinageRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
